baseURL = "https://yuta1402.github.io/test-blog/"
languageCode = "ja"
title = "Test Blog"
theme = "hugo-theme-minos"
canonifyurls = true

disqusShortname = "test-blog-vlsjnmkuqh"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  smartToc = true

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = -110
