version: 2
jobs:
  deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Deploy
          command: make publish
workflows:
  version: 2
  main:
    jobs:
      - deploy
