version: 2
jobs:
  deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - checkout
      - run:
          name: Deploy
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            make init
            make publish

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
